# Generated by Django 3.1.7 on 2021-03-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='description',
        ),
        migrations.AddField(
            model_name='snack',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
