# Generated by Django 3.1.7 on 2021-03-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_auto_20210311_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='name',
            new_name='snack',
        ),
    ]
